site:
  title: Wой Wаленький Wайт
# Загловок сайта
  start_page: mycomponent:kabanchik:meetingScript.adoc
# Начальная страница
content:
  sources:
    - url: .
      start_path: projects/Vasya
  branches: main
# Источники
ui:
  bundle:
    url: ./ui-bundle.zip
    supplemental_files:
    - path: ui.yml
      contents: |
        static_files: [ .nojekyll ]
    - path: .nojekyll
# Упаковка с интерфейсом и отключить бесячий jekyll
output:
  dir: docs
# Куда складывать файлы сайта